# Copyright (C) 2019-2020 The LineageOS Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/oppo/RMX1801/setup-makefiles.sh

PRODUCT_SOONG_NAMESPACES += \
    vendor/oppo/RMX1801

PRODUCT_COPY_FILES += \
    vendor/oppo/RMX1801/proprietary/bin/wfdservice:$(TARGET_COPY_OUT_SYSTEM)/bin/wfdservice \
    vendor/oppo/RMX1801/proprietary/etc/firmware/cpp_firmware_v1_10_0.fw:$(TARGET_COPY_OUT_SYSTEM)/etc/firmware/cpp_firmware_v1_10_0.fw \
    vendor/oppo/RMX1801/proprietary/etc/firmware/cpp_firmware_v1_12_0.fw:$(TARGET_COPY_OUT_SYSTEM)/etc/firmware/cpp_firmware_v1_12_0.fw \
    vendor/oppo/RMX1801/proprietary/etc/firmware/cpp_firmware_v1_1_1.fw:$(TARGET_COPY_OUT_SYSTEM)/etc/firmware/cpp_firmware_v1_1_1.fw \
    vendor/oppo/RMX1801/proprietary/etc/firmware/cpp_firmware_v1_1_6.fw:$(TARGET_COPY_OUT_SYSTEM)/etc/firmware/cpp_firmware_v1_1_6.fw \
    vendor/oppo/RMX1801/proprietary/etc/firmware/cpp_firmware_v1_2_0.fw:$(TARGET_COPY_OUT_SYSTEM)/etc/firmware/cpp_firmware_v1_2_0.fw \
    vendor/oppo/RMX1801/proprietary/etc/firmware/cpp_firmware_v1_4_0.fw:$(TARGET_COPY_OUT_SYSTEM)/etc/firmware/cpp_firmware_v1_4_0.fw \
    vendor/oppo/RMX1801/proprietary/etc/firmware/cpp_firmware_v1_5_0.fw:$(TARGET_COPY_OUT_SYSTEM)/etc/firmware/cpp_firmware_v1_5_0.fw \
    vendor/oppo/RMX1801/proprietary/etc/firmware/cpp_firmware_v1_5_1.fw:$(TARGET_COPY_OUT_SYSTEM)/etc/firmware/cpp_firmware_v1_5_1.fw \
    vendor/oppo/RMX1801/proprietary/etc/firmware/cpp_firmware_v1_5_2.fw:$(TARGET_COPY_OUT_SYSTEM)/etc/firmware/cpp_firmware_v1_5_2.fw \
    vendor/oppo/RMX1801/proprietary/etc/firmware/cpp_firmware_v1_6_0.fw:$(TARGET_COPY_OUT_SYSTEM)/etc/firmware/cpp_firmware_v1_6_0.fw \
    vendor/oppo/RMX1801/proprietary/etc/firmware/cpp_firmware_v1_8_0.fw:$(TARGET_COPY_OUT_SYSTEM)/etc/firmware/cpp_firmware_v1_8_0.fw \
    vendor/oppo/RMX1801/proprietary/etc/init/wfdservice.rc:$(TARGET_COPY_OUT_SYSTEM)/etc/init/wfdservice.rc \
    vendor/oppo/RMX1801/proprietary/etc/permissions/embms.xml:$(TARGET_COPY_OUT_SYSTEM)/etc/permissions/embms.xml \
    vendor/oppo/RMX1801/proprietary/etc/permissions/qcrilhook.xml:$(TARGET_COPY_OUT_SYSTEM)/etc/permissions/qcrilhook.xml \
    vendor/oppo/RMX1801/proprietary/etc/permissions/qti_libpermissions.xml:$(TARGET_COPY_OUT_SYSTEM)/etc/permissions/qti_libpermissions.xml \
    vendor/oppo/RMX1801/proprietary/etc/permissions/qti_permissions.xml:$(TARGET_COPY_OUT_SYSTEM)/etc/permissions/qti_permissions.xml \
    vendor/oppo/RMX1801/proprietary/etc/permissions/telephonyservice.xml:$(TARGET_COPY_OUT_SYSTEM)/etc/permissions/telephonyservice.xml \
    vendor/oppo/RMX1801/proprietary/etc/vstab_configs/GyroOffset_db.config:$(TARGET_COPY_OUT_SYSTEM)/etc/vstab_configs/GyroOffset_db.config \
    vendor/oppo/RMX1801/proprietary/etc/vstab_configs/fsync_db.config:$(TARGET_COPY_OUT_SYSTEM)/etc/vstab_configs/fsync_db.config \
    vendor/oppo/RMX1801/proprietary/etc/vstab_configs/vstab_db_1080p_preview.config:$(TARGET_COPY_OUT_SYSTEM)/etc/vstab_configs/vstab_db_1080p_preview.config \
    vendor/oppo/RMX1801/proprietary/etc/vstab_configs/vstab_db_1080p_preview_0_imx519_bmi.config:$(TARGET_COPY_OUT_SYSTEM)/etc/vstab_configs/vstab_db_1080p_preview_0_imx519_bmi.config \
    vendor/oppo/RMX1801/proprietary/etc/vstab_configs/vstab_db_1080p_preview_0_imx519_lsm.config:$(TARGET_COPY_OUT_SYSTEM)/etc/vstab_configs/vstab_db_1080p_preview_0_imx519_lsm.config \
    vendor/oppo/RMX1801/proprietary/etc/vstab_configs/vstab_db_1080p_video_0.config:$(TARGET_COPY_OUT_SYSTEM)/etc/vstab_configs/vstab_db_1080p_video_0.config \
    vendor/oppo/RMX1801/proprietary/etc/vstab_configs/vstab_db_1080p_video_0_imx519_bmi.config:$(TARGET_COPY_OUT_SYSTEM)/etc/vstab_configs/vstab_db_1080p_video_0_imx519_bmi.config \
    vendor/oppo/RMX1801/proprietary/etc/vstab_configs/vstab_db_1080p_video_0_imx519_lsm.config:$(TARGET_COPY_OUT_SYSTEM)/etc/vstab_configs/vstab_db_1080p_video_0_imx519_lsm.config \
    vendor/oppo/RMX1801/proprietary/etc/vstab_configs/vstab_db_1080p_video_0_s5k2p7sq.config:$(TARGET_COPY_OUT_SYSTEM)/etc/vstab_configs/vstab_db_1080p_video_0_s5k2p7sq.config \
    vendor/oppo/RMX1801/proprietary/etc/vstab_configs/vstab_db_1080p_video_0_s5k2p7sq_sfov.config:$(TARGET_COPY_OUT_SYSTEM)/etc/vstab_configs/vstab_db_1080p_video_0_s5k2p7sq_sfov.config \
    vendor/oppo/RMX1801/proprietary/etc/vstab_configs/vstab_db_1080p_video_0_s5k2p7sq_sfov_bmi.config:$(TARGET_COPY_OUT_SYSTEM)/etc/vstab_configs/vstab_db_1080p_video_0_s5k2p7sq_sfov_bmi.config \
    vendor/oppo/RMX1801/proprietary/etc/vstab_configs/vstab_db_1080p_video_0_s5k2p7sq_sfov_main.config:$(TARGET_COPY_OUT_SYSTEM)/etc/vstab_configs/vstab_db_1080p_video_0_s5k2p7sq_sfov_main.config \
    vendor/oppo/RMX1801/proprietary/etc/vstab_configs/vstab_db_1080p_video_0_sfov.config:$(TARGET_COPY_OUT_SYSTEM)/etc/vstab_configs/vstab_db_1080p_video_0_sfov.config \
    vendor/oppo/RMX1801/proprietary/etc/vstab_configs/vstab_db_1080p_video_0_sfov_lsm.config:$(TARGET_COPY_OUT_SYSTEM)/etc/vstab_configs/vstab_db_1080p_video_0_sfov_lsm.config \
    vendor/oppo/RMX1801/proprietary/etc/vstab_configs/vstab_db_1080p_video_0_sfov_main.config:$(TARGET_COPY_OUT_SYSTEM)/etc/vstab_configs/vstab_db_1080p_video_0_sfov_main.config \
    vendor/oppo/RMX1801/proprietary/etc/vstab_configs/vstab_db_1080p_video_1.config:$(TARGET_COPY_OUT_SYSTEM)/etc/vstab_configs/vstab_db_1080p_video_1.config \
    vendor/oppo/RMX1801/proprietary/etc/vstab_configs/vstab_db_1350p_video_0.config:$(TARGET_COPY_OUT_SYSTEM)/etc/vstab_configs/vstab_db_1350p_video_0.config \
    vendor/oppo/RMX1801/proprietary/etc/vstab_configs/vstab_db_1350p_video_0_s5k2p7sq.config:$(TARGET_COPY_OUT_SYSTEM)/etc/vstab_configs/vstab_db_1350p_video_0_s5k2p7sq.config \
    vendor/oppo/RMX1801/proprietary/etc/vstab_configs/vstab_db_4k_preview.config:$(TARGET_COPY_OUT_SYSTEM)/etc/vstab_configs/vstab_db_4k_preview.config \
    vendor/oppo/RMX1801/proprietary/etc/vstab_configs/vstab_db_4k_video_0.config:$(TARGET_COPY_OUT_SYSTEM)/etc/vstab_configs/vstab_db_4k_video_0.config \
    vendor/oppo/RMX1801/proprietary/etc/vstab_configs/vstab_db_4k_video_1.config:$(TARGET_COPY_OUT_SYSTEM)/etc/vstab_configs/vstab_db_4k_video_1.config \
    vendor/oppo/RMX1801/proprietary/etc/vstab_configs/vstab_db_720p_preview.config:$(TARGET_COPY_OUT_SYSTEM)/etc/vstab_configs/vstab_db_720p_preview.config \
    vendor/oppo/RMX1801/proprietary/etc/vstab_configs/vstab_db_720p_preview_0_imx519_bmi.config:$(TARGET_COPY_OUT_SYSTEM)/etc/vstab_configs/vstab_db_720p_preview_0_imx519_bmi.config \
    vendor/oppo/RMX1801/proprietary/etc/vstab_configs/vstab_db_720p_preview_0_imx519_lsm.config:$(TARGET_COPY_OUT_SYSTEM)/etc/vstab_configs/vstab_db_720p_preview_0_imx519_lsm.config \
    vendor/oppo/RMX1801/proprietary/etc/vstab_configs/vstab_db_720p_video_0.config:$(TARGET_COPY_OUT_SYSTEM)/etc/vstab_configs/vstab_db_720p_video_0.config \
    vendor/oppo/RMX1801/proprietary/etc/vstab_configs/vstab_db_720p_video_0_imx519_bmi.config:$(TARGET_COPY_OUT_SYSTEM)/etc/vstab_configs/vstab_db_720p_video_0_imx519_bmi.config \
    vendor/oppo/RMX1801/proprietary/etc/vstab_configs/vstab_db_720p_video_0_imx519_lsm.config:$(TARGET_COPY_OUT_SYSTEM)/etc/vstab_configs/vstab_db_720p_video_0_imx519_lsm.config \
    vendor/oppo/RMX1801/proprietary/etc/vstab_configs/vstab_db_720p_video_0_s5k2p7sq.config:$(TARGET_COPY_OUT_SYSTEM)/etc/vstab_configs/vstab_db_720p_video_0_s5k2p7sq.config \
    vendor/oppo/RMX1801/proprietary/etc/vstab_configs/vstab_db_720p_video_0_s5k2p7sq_sfov.config:$(TARGET_COPY_OUT_SYSTEM)/etc/vstab_configs/vstab_db_720p_video_0_s5k2p7sq_sfov.config \
    vendor/oppo/RMX1801/proprietary/etc/vstab_configs/vstab_db_720p_video_0_s5k2p7sq_sfov_bmi.config:$(TARGET_COPY_OUT_SYSTEM)/etc/vstab_configs/vstab_db_720p_video_0_s5k2p7sq_sfov_bmi.config \
    vendor/oppo/RMX1801/proprietary/etc/vstab_configs/vstab_db_720p_video_0_s5k2p7sq_sfov_main.config:$(TARGET_COPY_OUT_SYSTEM)/etc/vstab_configs/vstab_db_720p_video_0_s5k2p7sq_sfov_main.config \
    vendor/oppo/RMX1801/proprietary/etc/vstab_configs/vstab_db_720p_video_0_sfov.config:$(TARGET_COPY_OUT_SYSTEM)/etc/vstab_configs/vstab_db_720p_video_0_sfov.config \
    vendor/oppo/RMX1801/proprietary/etc/vstab_configs/vstab_db_720p_video_0_sfov_lsm.config:$(TARGET_COPY_OUT_SYSTEM)/etc/vstab_configs/vstab_db_720p_video_0_sfov_lsm.config \
    vendor/oppo/RMX1801/proprietary/etc/vstab_configs/vstab_db_720p_video_0_sfov_main.config:$(TARGET_COPY_OUT_SYSTEM)/etc/vstab_configs/vstab_db_720p_video_0_sfov_main.config \
    vendor/oppo/RMX1801/proprietary/etc/vstab_configs/vstab_db_720p_video_1.config:$(TARGET_COPY_OUT_SYSTEM)/etc/vstab_configs/vstab_db_720p_video_1.config \
    vendor/oppo/RMX1801/proprietary/etc/vstab_configs/vstab_db_900p_video_0.config:$(TARGET_COPY_OUT_SYSTEM)/etc/vstab_configs/vstab_db_900p_video_0.config \
    vendor/oppo/RMX1801/proprietary/etc/vstab_configs/vstab_db_900p_video_0_s5k2p7sq.config:$(TARGET_COPY_OUT_SYSTEM)/etc/vstab_configs/vstab_db_900p_video_0_s5k2p7sq.config \
    vendor/oppo/RMX1801/proprietary/etc/wfdconfig.xml:$(TARGET_COPY_OUT_SYSTEM)/etc/wfdconfig.xml \
    vendor/oppo/RMX1801/proprietary/etc/wfdconfigsink.xml:$(TARGET_COPY_OUT_SYSTEM)/etc/wfdconfigsink.xml \
    vendor/oppo/RMX1801/proprietary/framework/QtiTelephonyServicelibrary.jar:$(TARGET_COPY_OUT_SYSTEM)/framework/QtiTelephonyServicelibrary.jar \
    vendor/oppo/RMX1801/proprietary/framework/embmslibrary.jar:$(TARGET_COPY_OUT_SYSTEM)/framework/embmslibrary.jar \
    vendor/oppo/RMX1801/proprietary/framework/qcrilhook.jar:$(TARGET_COPY_OUT_SYSTEM)/framework/qcrilhook.jar \
    vendor/oppo/RMX1801/proprietary/framework/qti-telephony-common.jar:$(TARGET_COPY_OUT_SYSTEM)/framework/qti-telephony-common.jar \
    vendor/oppo/RMX1801/proprietary/framework/vendor.qti.hardware.alarm-V1.0-java.jar:$(TARGET_COPY_OUT_SYSTEM)/framework/vendor.qti.hardware.alarm-V1.0-java.jar \
    vendor/oppo/RMX1801/proprietary/lib/com.qualcomm.qti.wifidisplayhal@1.0.so:$(TARGET_COPY_OUT_SYSTEM)/lib/com.qualcomm.qti.wifidisplayhal@1.0.so \
    vendor/oppo/RMX1801/proprietary/lib/extractors/libmmparser.so:$(TARGET_COPY_OUT_SYSTEM)/lib/extractors/libmmparser.so \
    vendor/oppo/RMX1801/proprietary/lib/libFileMux.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libFileMux.so \
    vendor/oppo/RMX1801/proprietary/lib/libOmxMux.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libOmxMux.so \
    vendor/oppo/RMX1801/proprietary/lib/libdisplayconfig.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libdisplayconfig.so \
    vendor/oppo/RMX1801/proprietary/lib/libmmosal.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libmmosal.so \
    vendor/oppo/RMX1801/proprietary/lib/libmmparser_lite.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libmmparser_lite.so \
    vendor/oppo/RMX1801/proprietary/lib/libmmrtpdecoder.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libmmrtpdecoder.so \
    vendor/oppo/RMX1801/proprietary/lib/libmmrtpencoder.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libmmrtpencoder.so \
    vendor/oppo/RMX1801/proprietary/lib/libqdMetaData.system.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libqdMetaData.system.so \
    vendor/oppo/RMX1801/proprietary/lib/libwfdavenhancements.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libwfdavenhancements.so \
    vendor/oppo/RMX1801/proprietary/lib/libwfdclient.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libwfdclient.so \
    vendor/oppo/RMX1801/proprietary/lib/libwfdcodecv4l2.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libwfdcodecv4l2.so \
    vendor/oppo/RMX1801/proprietary/lib/libwfdcommonutils.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libwfdcommonutils.so \
    vendor/oppo/RMX1801/proprietary/lib/libwfdconfigutils.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libwfdconfigutils.so \
    vendor/oppo/RMX1801/proprietary/lib/libwfdmminterface.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libwfdmminterface.so \
    vendor/oppo/RMX1801/proprietary/lib/libwfdmmsink.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libwfdmmsink.so \
    vendor/oppo/RMX1801/proprietary/lib/libwfdmmsrc.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libwfdmmsrc.so \
    vendor/oppo/RMX1801/proprietary/lib/libwfdnative.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libwfdnative.so \
    vendor/oppo/RMX1801/proprietary/lib/libwfdrtsp.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libwfdrtsp.so \
    vendor/oppo/RMX1801/proprietary/lib/libwfdservice.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libwfdservice.so \
    vendor/oppo/RMX1801/proprietary/lib/libwfdsm.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libwfdsm.so \
    vendor/oppo/RMX1801/proprietary/lib/libwfduibcinterface.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libwfduibcinterface.so \
    vendor/oppo/RMX1801/proprietary/lib/libwfduibcsink.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libwfduibcsink.so \
    vendor/oppo/RMX1801/proprietary/lib/libwfduibcsinkinterface.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libwfduibcsinkinterface.so \
    vendor/oppo/RMX1801/proprietary/lib/libwfduibcsrc.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libwfduibcsrc.so \
    vendor/oppo/RMX1801/proprietary/lib/libwfduibcsrcinterface.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libwfduibcsrcinterface.so \
    vendor/oppo/RMX1801/proprietary/lib64/lib-imsvideocodec.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/lib-imsvideocodec.so \
    vendor/oppo/RMX1801/proprietary/lib64/lib-imsvt.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/lib-imsvt.so \
    vendor/oppo/RMX1801/proprietary/lib64/lib-imsvtextutils.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/lib-imsvtextutils.so \
    vendor/oppo/RMX1801/proprietary/lib64/lib-imsvtutils.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/lib-imsvtutils.so \
    vendor/oppo/RMX1801/proprietary/lib64/libdiag_system.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/libdiag_system.so \
    vendor/oppo/RMX1801/proprietary/lib64/libimscamera_jni.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/libimscamera_jni.so \
    vendor/oppo/RMX1801/proprietary/lib64/libimsmedia_jni.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/libimsmedia_jni.so \
    vendor/oppo/RMX1801/proprietary/lib64/libmmosal.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/libmmosal.so \
    vendor/oppo/RMX1801/proprietary/lib64/librcc.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/librcc.so \
    vendor/oppo/RMX1801/proprietary/lib64/libsdm-disp-apis.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/libsdm-disp-apis.so \
    vendor/oppo/RMX1801/proprietary/lib64/libwfdclient.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/libwfdclient.so \
    vendor/oppo/RMX1801/proprietary/lib64/libwfdnative.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/libwfdnative.so \
    vendor/oppo/RMX1801/proprietary/lib64/vendor.display.color@1.0.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/vendor.display.color@1.0.so \
    vendor/oppo/RMX1801/proprietary/lib64/vendor.qti.imsrtpservice@1.0.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/vendor.qti.imsrtpservice@1.0.so \
    vendor/oppo/RMX1801/proprietary/lib/soundfx/libvolumelistener.so:$(TARGET_COPY_OUT_SYSTEM)/lib/soundfx/libvolumelistener.so \
    vendor/oppo/RMX1801/proprietary/lib64/soundfx/libvolumelistener.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/soundfx/libvolumelistener.so

PRODUCT_PACKAGES += \
    QtiTelephonyService \
    embms \
    WfdService \
    ims \
    qcrilmsgtunnel \
    WfdCommon
